with open ("Search_bar_#.txt","w") as output:
    x=0
    y=1
    with open ("KMS_Production_Computer_Inventory.csv","r") as input:
        data=input.readlines()
        for i in data:
            strofitems=data[x].split(",")
            x=x+1
            if len(strofitems[8]) <= 17:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 18 and len(strofitems[8]) <= 35:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 36 and len(strofitems[8]) <= 53:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 54 and len(strofitems[8]) <= 71:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 72 and len(strofitems[8]) <= 89:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 90 and len(strofitems[8]) <= 107:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][90:107])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 108 and len(strofitems[8]) <= 125:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][90:107])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][108:125])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 126 and len(strofitems[8]) <= 143:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][90:107])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][108:125])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][126:143])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 144 and len(strofitems[8]) <= 161:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][90:107])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][108:125])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][126:143])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][144:161])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1
            elif len(strofitems[8]) >= 162 and len(strofitems[8]) <= 179:
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][0:17])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][18:35])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][36:53])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][54:71])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][72:89])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][90:107])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][108:125])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][126:143])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][144:161])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                output.write("    if (search ==\"%s\") {\n"%strofitems[8][162:179])
                output.write("    document.getElementById(\"link%d\").innerHTML=\n"%y)
                output.write("    \"Computer %d\";\n"%y)
                output.write("    }\n")
                y=y+1